<a href="https://colab.research.google.com/github/Aleemashahadiya/PYTHON/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

vec = np.array([1,2,3,3])
print(f"vector:\n{vec}")

matrix = np.array([[1,2,3,4], [4,5,6,4]])
print(f"\nmatrix:\n{matrix}")

result= vec + matrix
print(f"sum of vec&matrix:\n{result}")
print(f"Type of vec:{type(vec)}")
print(f"Type of object:{type(matrix)}")

vector:
[1 2 3 3]

matrix:
[[1 2 3 4]
 [4 5 6 4]]
sum of vec&matrix:
[[2 4 6 7]
 [5 7 9 7]]
Type of vec:<class 'numpy.ndarray'>
Type of object:<class 'numpy.ndarray'>


In [2]:
import numpy as np

matrix_a = np.array([[1, 2],[3, 4]])

matrix_b = np.array([[10, 20],[30, 40]])

element_wise_product = matrix_a * matrix_b
print(element_wise_product)

product=matrix_a @ matrix_b
print(product)
product=np.dot(matrix_a,matrix_b)
print(product)

[[ 10  40]
 [ 90 160]]
[[ 70 100]
 [150 220]]
[[ 70 100]
 [150 220]]


In [3]:
import numpy as np

matrix_a1 = np.array([[0.5, 2.1, -1.0], [0.9, 0.1, 0.4]])

matrix_a2 = np.array([10, 5, 2])

scores = np.dot(matrix_a1,matrix_a2 )
print(scores)

[13.5 10.3]


In [4]:
import numpy as np
sales_data = np.array([[10, 20, 15, 25],
                       [30, 22, 35, 40],
                       [12, 28, 33, 30]])

print("Sales Data:\n", sales_data)

daily_totals = sales_data.sum(axis=0)#column
print(f"\nTotal sales per day (axis=0): {daily_totals}")

product_totals = sales_data.sum(axis=1)#row
print(f"Total sales per product (axis=1): {product_totals}")

max_daily_sale = sales_data.max(axis=0)
print(f"\nMax sale each day (axis=0): {max_daily_sale}")

max_product_sale = sales_data.max(axis=1)
print(f"Max sale for each product (axis=1): {max_product_sale}")

Sales Data:
 [[10 20 15 25]
 [30 22 35 40]
 [12 28 33 30]]

Total sales per day (axis=0): [52 70 83 95]
Total sales per product (axis=1): [ 70 127 103]

Max sale each day (axis=0): [30 28 35 40]
Max sale for each product (axis=1): [25 40 33]
